Поправки в документацию
vare-team/sdc-docs pull request #14
Opened 2021-05-26 21:49 UTC by TheKing-OfTime

Поправки в документацию, которые улучшили описание некоторых тонкостей SD.C API

2021-05-29 14:00 UTC, vlfz requested changes
То как ты пофиксил в описании побитовые значения - скорее всего при проверке значки будут некорректно отображаться

2021-05-30 08:03 UTC, TheKing-OfTime commented
Я проверял. Всё работает в штатном режиме)

2021-05-31 12:58 UTC, D3rise commented on api/site/guild.md
> +status & 32  //True (Пасхантер)
Изменение константного значения;
От изменения доков API не поменяется, нельзя менять значение одного из операндов логического И без внесения соответствующих изменений в код основного проекта

2021-05-31 13:08 UTC, D3rise commented on api/site/guild.md
> +status & 32  //True (Пасхантер)
> Изменение константного значения;
> От изменения доков API не поменяется, нельзя менять значение одного из операндов логического И без внесения соответствующих изменений в код основного проекта

На самом деле, выполнение операций из исходного файла дают результат, не соответствующий комментариям, поэтому внесенные изменения действительно будут верны:
`40 & 10` = `true` (не соответствует ожидаемому значению из комментария)
`40 & 16` = `false` (соответствует)

`40 & 20` = `false` (не соответствует значению из комментария)
`40 & 32` = `true` (соответствует)

Поэтому внесенные изменения действительно верны

2021-06-02 18:57 UTC, merged